<a href="https://colab.research.google.com/github/nampy3/ncoder/blob/master/1806ML01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
#!/usr/bin/python3

import numpy as np

#creating 10 array

a=np.array([2,3,5,79])
b=np.array([12,13,15,179])

# adding same D array

c=a+b
print(c)

#mult

m=a*b
print(m)

#add particular value in each element of array

a5=a+5
print(a5)

[ 14  16  20 258]
[   24    39    75 14141]
[ 7  8 10 84]


In [0]:
x=np.array([[2,5,8],[3,6,1]])

In [37]:
print(x)

[[2 5 8]
 [3 6 1]]


In [38]:
y=x+7
print(7)

array([[ 9, 12, 15],
       [10, 13,  8]])

In [39]:
x*2

array([[ 4, 10, 16],
       [ 6, 12,  2]])

In [40]:
x**2

array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [41]:
x**3

array([[  8, 125, 512],
       [ 27, 216,   1]])