<a href="https://colab.research.google.com/github/nampy3/ncoder/blob/master/1806ML01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#!/usr/bin/python3

import numpy as np

#creating 10 array

a=np.array([2,3,5,79])
b=np.array([12,13,15,179])

# adding same D array

c=a+b
print(c)

#mult

m=a*b
print(m)

#add particular value in each element of array

a5=a+5
print(a5)

In [0]:
x=np.array([[2,5,8],[3,6,1]])

In [0]:
print(x)

In [0]:
y=x+7
print(7)

In [0]:
x*2

In [0]:
x**2

In [0]:
x**3

In [0]:
x.shape


In [0]:
z= np.array([[2,7],[3,8],[2,9],[9,4]])
z

In [0]:
z.shape

In [0]:
z[0:2]

In [48]:
z[0:]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [49]:
z[0:,0]

array([2, 3, 2, 9])

In [50]:
x[0:,1]

array([5, 6])

In [51]:
x[0:,0:2]

array([[2, 5],
       [3, 6]])

In [55]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [58]:
z[[0,3],1]

array([7, 4])

In [62]:
b=numpy.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])
b

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [63]:
b[0:,1]

array([9, 2, 5, 9])

In [64]:
b[0:,[2]]

array([[7],
       [8],
       [6],
       [0]])

In [65]:
b[0:,2]

array([7, 8, 6, 0])

In [66]:
b[1:3,1]

array([2, 5])

In [67]:
b[1:,2]

array([8, 6, 0])

In [68]:
b[1:,[0,2]]

array([[3, 8],
       [4, 6],
       [2, 0]])

In [69]:
x.reshape(3,2)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
x1=x.reshape(3,2)

In [71]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [74]:
np.zeros((40,70))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [75]:
np.full((4,5),98)

array([[98, 98, 98, 98, 98],
       [98, 98, 98, 98, 98],
       [98, 98, 98, 98, 98],
       [98, 98, 98, 98, 98]])